/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 kobold.glb
*/

import React, { useRef, Suspense } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

export function Kobold(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('3dModels/kobold.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001" position={[0.25, 4.42, -0.32]} rotation={[-2.83, 1.41, 2.84]} scale={0.3}>
          <primitive object={nodes.Bone} />
          <skinnedMesh name="2Chest" geometry={nodes['2Chest'].geometry} material={materials['Material.001']} skeleton={nodes['2Chest'].skeleton} />
        </group>
        <mesh name="Desk" geometry={nodes.Desk.geometry} material={materials.Material} position={[0, 0, 1.95]} scale={[4.71, 1, 2.41]} />
        <mesh name="Chair" geometry={nodes.Chair.geometry} material={materials['Material.001']} position={[0.51, 0.25, -0.49]} rotation={[-Math.PI, 1.44, -Math.PI]} scale={[1.14, 1, 0.2]} />
        <mesh name="Desk001" geometry={nodes.Desk001.geometry} material={materials.Material} position={[0, 0, 1.95]} scale={[4.71, 1, 2.41]} />
      </group>
    </group>
  )
}

export default function App() {
  return(
<Canvas style={{ background: "#171717" }}>
<ambientLight intensity={1} />
<spotLight intensity={0.5} angle={0.1} penumbra={1} position={[10, 15, 10]} castShadow />
  <Suspense fallback={null}>
      <Kobold />
   </Suspense>
</Canvas>
)};

useGLTF.preload('/3dModels/kobold.glb')
